// header
import './components/menu.js';
import './components/logo.js';
import './components/menu-toggle.js'
import './components/nav.js'
import './components/button-box.js'
// main
import './components/main.js'
import './components/hero.js';
import './components/contador.js';
import './components/banner-inicio.js'
import './components/services.js'
import './components/trainer.js'
import './components/precios.js'
import './components/galeria.js'
// footer
import './components/footer.js'
import './components/footer-info.js'
import './components/footer-service.js'
import './components/footer-page.js'
import './components/footer-address.js'
import './components/footer-copyright.js'